//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace RR2.Statics {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Map {
        
        private BuildingType[] buildingTypesField;
        
        private VehicleType[] vehicleTypesField;
        
        private ObjectType[] objectTypesField;
        
        private TileType[] tileTypesField;
        
        private PathType[] pathTypesField;
        
        private RockRaider rockRaiderField;
        
        private ToolType[] toolTypesField;
        
        private MapData mapDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BuildingType[] BuildingTypes {
            get {
                return this.buildingTypesField;
            }
            set {
                this.buildingTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VehicleType[] VehicleTypes {
            get {
                return this.vehicleTypesField;
            }
            set {
                this.vehicleTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ObjectType[] ObjectTypes {
            get {
                return this.objectTypesField;
            }
            set {
                this.objectTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TileType[] TileTypes {
            get {
                return this.tileTypesField;
            }
            set {
                this.tileTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PathType[] PathTypes {
            get {
                return this.pathTypesField;
            }
            set {
                this.pathTypesField = value;
            }
        }
        
        /// <remarks/>
        public RockRaider RockRaider {
            get {
                return this.rockRaiderField;
            }
            set {
                this.rockRaiderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ToolType[] ToolTypes {
            get {
                return this.toolTypesField;
            }
            set {
                this.toolTypesField = value;
            }
        }
        
        /// <remarks/>
        public MapData MapData {
            get {
                return this.mapDataField;
            }
            set {
                this.mapDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuildingType {
        
        private Requires requiresField;
        
        private int buildingTypeIdField;
        
        private string nameField;
        
        private string modelPathField;
        
        private int healthField;
        
        /// <remarks/>
        public Requires Requires {
            get {
                return this.requiresField;
            }
            set {
                this.requiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BuildingTypeId {
            get {
                return this.buildingTypeIdField;
            }
            set {
                this.buildingTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ModelPath {
            get {
                return this.modelPathField;
            }
            set {
                this.modelPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Health {
            get {
                return this.healthField;
            }
            set {
                this.healthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Requires {
        
        private string requiredObjectsField;
        
        private RequiredBuilding[] requiredBuildingsField;
        
        private int numberOfRaidersField;
        
        private bool numberOfRaidersFieldSpecified;
        
        /// <remarks/>
        public string RequiredObjects {
            get {
                return this.requiredObjectsField;
            }
            set {
                this.requiredObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RequiredBuilding[] RequiredBuildings {
            get {
                return this.requiredBuildingsField;
            }
            set {
                this.requiredBuildingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfRaiders {
            get {
                return this.numberOfRaidersField;
            }
            set {
                this.numberOfRaidersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfRaidersSpecified {
            get {
                return this.numberOfRaidersFieldSpecified;
            }
            set {
                this.numberOfRaidersFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequiredBuilding {
        
        private string buildingUpgradeIdsField;
        
        private int buildingTypeIdField;
        
        /// <remarks/>
        public string BuildingUpgradeIds {
            get {
                return this.buildingUpgradeIdsField;
            }
            set {
                this.buildingUpgradeIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BuildingTypeId {
            get {
                return this.buildingTypeIdField;
            }
            set {
                this.buildingTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tile {
        
        private string[] extraDropIdsField;
        
        private int tileTypeIdField;
        
        private int tileIdField;
        
        private float heightField;
        
        private int pathTypeIdField;
        
        private bool pathTypeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtraDropIds")]
        public string[] ExtraDropIds {
            get {
                return this.extraDropIdsField;
            }
            set {
                this.extraDropIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TileTypeId {
            get {
                return this.tileTypeIdField;
            }
            set {
                this.tileTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TileId {
            get {
                return this.tileIdField;
            }
            set {
                this.tileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PathTypeId {
            get {
                return this.pathTypeIdField;
            }
            set {
                this.pathTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PathTypeIdSpecified {
            get {
                return this.pathTypeIdFieldSpecified;
            }
            set {
                this.pathTypeIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Object {
        
        private Pos3 positionField;
        
        private int objectTypeIdField;
        
        private int objectIdField;
        
        /// <remarks/>
        public Pos3 Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ObjectTypeId {
            get {
                return this.objectTypeIdField;
            }
            set {
                this.objectTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pos3 {
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Building {
        
        private string buildingUpgradeIdsField;
        
        private int buildingTypeIdField;
        
        private int buildingIdField;
        
        private int parentTileField;
        
        /// <remarks/>
        public string BuildingUpgradeIds {
            get {
                return this.buildingUpgradeIdsField;
            }
            set {
                this.buildingUpgradeIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BuildingTypeId {
            get {
                return this.buildingTypeIdField;
            }
            set {
                this.buildingTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BuildingId {
            get {
                return this.buildingIdField;
            }
            set {
                this.buildingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ParentTile {
            get {
                return this.parentTileField;
            }
            set {
                this.parentTileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Raider {
        
        private Pos3 positionField;
        
        private int raiderIdField;
        
        private string nameField;
        
        /// <remarks/>
        public Pos3 Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RaiderId {
            get {
                return this.raiderIdField;
            }
            set {
                this.raiderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapData {
        
        private Raider[] raidersField;
        
        private Building[] buildingsField;
        
        private Object[] objectsField;
        
        private Tile[] tilesField;
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Raider[] Raiders {
            get {
                return this.raidersField;
            }
            set {
                this.raidersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Building[] Buildings {
            get {
                return this.buildingsField;
            }
            set {
                this.buildingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Object[] Objects {
            get {
                return this.objectsField;
            }
            set {
                this.objectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Tile[] Tiles {
            get {
                return this.tilesField;
            }
            set {
                this.tilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ToolType {
        
        private DropRequires dropRequiresField;
        
        private float toolTypeIdField;
        
        private string nameField;
        
        private string modelPathField;
        
        /// <remarks/>
        public DropRequires DropRequires {
            get {
                return this.dropRequiresField;
            }
            set {
                this.dropRequiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ToolTypeId {
            get {
                return this.toolTypeIdField;
            }
            set {
                this.toolTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ModelPath {
            get {
                return this.modelPathField;
            }
            set {
                this.modelPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DropRequires {
        
        private string requiredRaiderUpgradesField;
        
        private RequiredBuilding[] acceptBuildingsField;
        
        private RequiredBuilding[] dropBuildingsField;
        
        /// <remarks/>
        public string RequiredRaiderUpgrades {
            get {
                return this.requiredRaiderUpgradesField;
            }
            set {
                this.requiredRaiderUpgradesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AcceptBuilding", IsNullable=false)]
        public RequiredBuilding[] AcceptBuildings {
            get {
                return this.acceptBuildingsField;
            }
            set {
                this.acceptBuildingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DropBuilding", IsNullable=false)]
        public RequiredBuilding[] DropBuildings {
            get {
                return this.dropBuildingsField;
            }
            set {
                this.dropBuildingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RockRaider {
        
        private string teleportedByIdsField;
        
        private Pos3 positionField;
        
        private string newMoveTypeField;
        
        private float speedField;
        
        private float surveyRadiusField;
        
        private float awarenessRangeField;
        
        private float drillMultiField;
        
        private float repairMultiField;
        
        private float tirednessRateField;
        
        private int healthField;
        
        private int numberOfToolsCanCarryField;
        
        private MoveType moveTypeField;
        
        private float oxygenDrainField;
        
        private float drillRadiusField;
        
        private string modelPathField;
        
        private int raiderIdField;
        
        private bool raiderIdFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public string TeleportedByIds {
            get {
                return this.teleportedByIdsField;
            }
            set {
                this.teleportedByIdsField = value;
            }
        }
        
        /// <remarks/>
        public Pos3 Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string NewMoveType {
            get {
                return this.newMoveTypeField;
            }
            set {
                this.newMoveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float SurveyRadius {
            get {
                return this.surveyRadiusField;
            }
            set {
                this.surveyRadiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AwarenessRange {
            get {
                return this.awarenessRangeField;
            }
            set {
                this.awarenessRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DrillMulti {
            get {
                return this.drillMultiField;
            }
            set {
                this.drillMultiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float RepairMulti {
            get {
                return this.repairMultiField;
            }
            set {
                this.repairMultiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float TirednessRate {
            get {
                return this.tirednessRateField;
            }
            set {
                this.tirednessRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Health {
            get {
                return this.healthField;
            }
            set {
                this.healthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfToolsCanCarry {
            get {
                return this.numberOfToolsCanCarryField;
            }
            set {
                this.numberOfToolsCanCarryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MoveType MoveType {
            get {
                return this.moveTypeField;
            }
            set {
                this.moveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OxygenDrain {
            get {
                return this.oxygenDrainField;
            }
            set {
                this.oxygenDrainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DrillRadius {
            get {
                return this.drillRadiusField;
            }
            set {
                this.drillRadiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ModelPath {
            get {
                return this.modelPathField;
            }
            set {
                this.modelPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RaiderId {
            get {
                return this.raiderIdField;
            }
            set {
                this.raiderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RaiderIdSpecified {
            get {
                return this.raiderIdFieldSpecified;
            }
            set {
                this.raiderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum MoveType {
        
        /// <remarks/>
        Land,
        
        /// <remarks/>
        Air,
        
        /// <remarks/>
        Water,
        
        /// <remarks/>
        LandWater,
        
        /// <remarks/>
        LandAir,
        
        /// <remarks/>
        AirWater,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathType {
        
        private int pathTypeIdField;
        
        private string nameField;
        
        private string texturePathField;
        
        private float moveMultiField;
        
        private bool shoveledField;
        
        private bool canBePoweredField;
        
        private bool canBePoweredFieldSpecified;
        
        private int destroysIntoField;
        
        private bool destroysIntoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PathTypeId {
            get {
                return this.pathTypeIdField;
            }
            set {
                this.pathTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string TexturePath {
            get {
                return this.texturePathField;
            }
            set {
                this.texturePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float MoveMulti {
            get {
                return this.moveMultiField;
            }
            set {
                this.moveMultiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Shoveled {
            get {
                return this.shoveledField;
            }
            set {
                this.shoveledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CanBePowered {
            get {
                return this.canBePoweredField;
            }
            set {
                this.canBePoweredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanBePoweredSpecified {
            get {
                return this.canBePoweredFieldSpecified;
            }
            set {
                this.canBePoweredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DestroysInto {
            get {
                return this.destroysIntoField;
            }
            set {
                this.destroysIntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DestroysIntoSpecified {
            get {
                return this.destroysIntoFieldSpecified;
            }
            set {
                this.destroysIntoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Drop {
        
        private int objectTypeIdField;
        
        private int minimumField;
        
        private int maximumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ObjectTypeId {
            get {
                return this.objectTypeIdField;
            }
            set {
                this.objectTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TileType {
        
        private Drop[] dropsField;
        
        private string newMoveTypeField;
        
        private string[] extraDropIdsField;
        
        private int tileTypeIdField;
        
        private int pathTypeIdField;
        
        private bool pathTypeIdFieldSpecified;
        
        private string nameField;
        
        private bool solidField;
        
        private string texturePathField;
        
        private float moveMultiField;
        
        private float drillTimeField;
        
        private MoveType moveTypeField;
        
        private int pathTypeDestroysIntoField;
        
        private bool pathTypeDestroysIntoFieldSpecified;
        
        private int tileTypeDestroysIntoField;
        
        private bool tileTypeDestroysIntoFieldSpecified;
        
        private float heightField;
        
        private bool heightFieldSpecified;
        
        private int tileIdField;
        
        private bool tileIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Drop[] Drops {
            get {
                return this.dropsField;
            }
            set {
                this.dropsField = value;
            }
        }
        
        /// <remarks/>
        public string NewMoveType {
            get {
                return this.newMoveTypeField;
            }
            set {
                this.newMoveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtraDropIds")]
        public string[] ExtraDropIds {
            get {
                return this.extraDropIdsField;
            }
            set {
                this.extraDropIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TileTypeId {
            get {
                return this.tileTypeIdField;
            }
            set {
                this.tileTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PathTypeId {
            get {
                return this.pathTypeIdField;
            }
            set {
                this.pathTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PathTypeIdSpecified {
            get {
                return this.pathTypeIdFieldSpecified;
            }
            set {
                this.pathTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Solid {
            get {
                return this.solidField;
            }
            set {
                this.solidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string TexturePath {
            get {
                return this.texturePathField;
            }
            set {
                this.texturePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float MoveMulti {
            get {
                return this.moveMultiField;
            }
            set {
                this.moveMultiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DrillTime {
            get {
                return this.drillTimeField;
            }
            set {
                this.drillTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MoveType MoveType {
            get {
                return this.moveTypeField;
            }
            set {
                this.moveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PathTypeDestroysInto {
            get {
                return this.pathTypeDestroysIntoField;
            }
            set {
                this.pathTypeDestroysIntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PathTypeDestroysIntoSpecified {
            get {
                return this.pathTypeDestroysIntoFieldSpecified;
            }
            set {
                this.pathTypeDestroysIntoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TileTypeDestroysInto {
            get {
                return this.tileTypeDestroysIntoField;
            }
            set {
                this.tileTypeDestroysIntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TileTypeDestroysIntoSpecified {
            get {
                return this.tileTypeDestroysIntoFieldSpecified;
            }
            set {
                this.tileTypeDestroysIntoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TileId {
            get {
                return this.tileIdField;
            }
            set {
                this.tileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TileIdSpecified {
            get {
                return this.tileIdFieldSpecified;
            }
            set {
                this.tileIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObjectType {
        
        private DropRequires dropRequiresField;
        
        private int objectTypeIdField;
        
        private string nameField;
        
        private int ecField;
        
        private int oreField;
        
        private float massField;
        
        private string modelPathField;
        
        /// <remarks/>
        public DropRequires DropRequires {
            get {
                return this.dropRequiresField;
            }
            set {
                this.dropRequiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ObjectTypeId {
            get {
                return this.objectTypeIdField;
            }
            set {
                this.objectTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EC {
            get {
                return this.ecField;
            }
            set {
                this.ecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Ore {
            get {
                return this.oreField;
            }
            set {
                this.oreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ModelPath {
            get {
                return this.modelPathField;
            }
            set {
                this.modelPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VehicleType {
        
        private string teleportedByIdsField;
        
        private Requires requiresField;
        
        private string newMoveTypeField;
        
        private int vehicleTypeIdField;
        
        private string nameField;
        
        private string modelPathField;
        
        private float massField;
        
        private float speedField;
        
        private float surveyRadiusField;
        
        private string sizeTypeField;
        
        private MoveType moveTypeField;
        
        private int healthField;
        
        /// <remarks/>
        public string TeleportedByIds {
            get {
                return this.teleportedByIdsField;
            }
            set {
                this.teleportedByIdsField = value;
            }
        }
        
        /// <remarks/>
        public Requires Requires {
            get {
                return this.requiresField;
            }
            set {
                this.requiresField = value;
            }
        }
        
        /// <remarks/>
        public string NewMoveType {
            get {
                return this.newMoveTypeField;
            }
            set {
                this.newMoveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int VehicleTypeId {
            get {
                return this.vehicleTypeIdField;
            }
            set {
                this.vehicleTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ModelPath {
            get {
                return this.modelPathField;
            }
            set {
                this.modelPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float SurveyRadius {
            get {
                return this.surveyRadiusField;
            }
            set {
                this.surveyRadiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string SizeType {
            get {
                return this.sizeTypeField;
            }
            set {
                this.sizeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MoveType MoveType {
            get {
                return this.moveTypeField;
            }
            set {
                this.moveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Health {
            get {
                return this.healthField;
            }
            set {
                this.healthField = value;
            }
        }
    }
}
